//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFood_Client.WebServiceEFood {
    using System.Xml.Serialization;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EFoodServiceSoap", Namespace="http://tempuri.org/")]
    public partial class EFoodService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidateConnectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExisteCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExisteChequeOperationCompleted;
        
        private System.Threading.SendOrPostCallback RealizaRebajoChequeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizaSaldoChequeOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertaCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertaChequeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExisteTarjetaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizaSaldoTarjetaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RealizaRebajoTarjetaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidaTarjetaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertaTarjetaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtieneSaldoTarjetaOperationCompleted;
        
        /// <remarks/>
        public EFoodService() {
            this.Url = "http://127.0.0.1:5002/Service.asmx";
        }
        
        public EFoodService(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        public event ValidateConnectionCompletedEventHandler ValidateConnectionCompleted;
        
        /// <remarks/>
        public event ExisteCuentaCompletedEventHandler ExisteCuentaCompleted;
        
        /// <remarks/>
        public event ExisteChequeCompletedEventHandler ExisteChequeCompleted;
        
        /// <remarks/>
        public event RealizaRebajoChequeCompletedEventHandler RealizaRebajoChequeCompleted;
        
        /// <remarks/>
        public event ActualizaSaldoChequeCompletedEventHandler ActualizaSaldoChequeCompleted;
        
        /// <remarks/>
        public event InsertaCuentaCompletedEventHandler InsertaCuentaCompleted;
        
        /// <remarks/>
        public event InsertaChequeCompletedEventHandler InsertaChequeCompleted;
        
        /// <remarks/>
        public event ExisteTarjetaCompletedEventHandler ExisteTarjetaCompleted;
        
        /// <remarks/>
        public event ActualizaSaldoTarjetaCompletedEventHandler ActualizaSaldoTarjetaCompleted;
        
        /// <remarks/>
        public event RealizaRebajoTarjetaCompletedEventHandler RealizaRebajoTarjetaCompleted;
        
        /// <remarks/>
        public event ValidaTarjetaCompletedEventHandler ValidaTarjetaCompleted;
        
        /// <remarks/>
        public event InsertaTarjetaCompletedEventHandler InsertaTarjetaCompleted;
        
        /// <remarks/>
        public event ObtieneSaldoTarjetaCompletedEventHandler ObtieneSaldoTarjetaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Valida_Conexion", RequestElementName="Valida_Conexion", RequestNamespace="http://tempuri.org/", ResponseElementName="Valida_ConexionResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Valida_ConexionResult")]
        public bool ValidateConnection() {
            object[] results = this.Invoke("ValidateConnection", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateConnectionAsync() {
            this.ValidateConnectionAsync(null);
        }
        
        /// <remarks/>
        public void ValidateConnectionAsync(object userState) {
            if ((this.ValidateConnectionOperationCompleted == null)) {
                this.ValidateConnectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateConnectionOperationCompleted);
            }
            this.InvokeAsync("ValidateConnection", new object[0], this.ValidateConnectionOperationCompleted, userState);
        }
        
        private void OnValidateConnectionOperationCompleted(object arg) {
            if ((this.ValidateConnectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateConnectionCompleted(this, new ValidateConnectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExisteCuenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ExisteCuenta(int cuenta) {
            object[] results = this.Invoke("ExisteCuenta", new object[] {
                        cuenta});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ExisteCuentaAsync(int cuenta) {
            this.ExisteCuentaAsync(cuenta, null);
        }
        
        /// <remarks/>
        public void ExisteCuentaAsync(int cuenta, object userState) {
            if ((this.ExisteCuentaOperationCompleted == null)) {
                this.ExisteCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExisteCuentaOperationCompleted);
            }
            this.InvokeAsync("ExisteCuenta", new object[] {
                        cuenta}, this.ExisteCuentaOperationCompleted, userState);
        }
        
        private void OnExisteCuentaOperationCompleted(object arg) {
            if ((this.ExisteCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExisteCuentaCompleted(this, new ExisteCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExisteCheque", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ExisteCheque(int cuenta, string numero) {
            object[] results = this.Invoke("ExisteCheque", new object[] {
                        cuenta,
                        numero});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ExisteChequeAsync(int cuenta, string numero) {
            this.ExisteChequeAsync(cuenta, numero, null);
        }
        
        /// <remarks/>
        public void ExisteChequeAsync(int cuenta, string numero, object userState) {
            if ((this.ExisteChequeOperationCompleted == null)) {
                this.ExisteChequeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExisteChequeOperationCompleted);
            }
            this.InvokeAsync("ExisteCheque", new object[] {
                        cuenta,
                        numero}, this.ExisteChequeOperationCompleted, userState);
        }
        
        private void OnExisteChequeOperationCompleted(object arg) {
            if ((this.ExisteChequeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExisteChequeCompleted(this, new ExisteChequeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RealizaRebajoCheque", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RealizaRebajoCheque(int cuenta, decimal monto) {
            object[] results = this.Invoke("RealizaRebajoCheque", new object[] {
                        cuenta,
                        monto});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RealizaRebajoChequeAsync(int cuenta, decimal monto) {
            this.RealizaRebajoChequeAsync(cuenta, monto, null);
        }
        
        /// <remarks/>
        public void RealizaRebajoChequeAsync(int cuenta, decimal monto, object userState) {
            if ((this.RealizaRebajoChequeOperationCompleted == null)) {
                this.RealizaRebajoChequeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRealizaRebajoChequeOperationCompleted);
            }
            this.InvokeAsync("RealizaRebajoCheque", new object[] {
                        cuenta,
                        monto}, this.RealizaRebajoChequeOperationCompleted, userState);
        }
        
        private void OnRealizaRebajoChequeOperationCompleted(object arg) {
            if ((this.RealizaRebajoChequeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RealizaRebajoChequeCompleted(this, new RealizaRebajoChequeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizaSaldoCheque", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ActualizaSaldoCheque(int cuenta, decimal monto) {
            object[] results = this.Invoke("ActualizaSaldoCheque", new object[] {
                        cuenta,
                        monto});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizaSaldoChequeAsync(int cuenta, decimal monto) {
            this.ActualizaSaldoChequeAsync(cuenta, monto, null);
        }
        
        /// <remarks/>
        public void ActualizaSaldoChequeAsync(int cuenta, decimal monto, object userState) {
            if ((this.ActualizaSaldoChequeOperationCompleted == null)) {
                this.ActualizaSaldoChequeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizaSaldoChequeOperationCompleted);
            }
            this.InvokeAsync("ActualizaSaldoCheque", new object[] {
                        cuenta,
                        monto}, this.ActualizaSaldoChequeOperationCompleted, userState);
        }
        
        private void OnActualizaSaldoChequeOperationCompleted(object arg) {
            if ((this.ActualizaSaldoChequeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizaSaldoChequeCompleted(this, new ActualizaSaldoChequeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertaCuenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertaCuenta(int cuenta, decimal saldo) {
            object[] results = this.Invoke("InsertaCuenta", new object[] {
                        cuenta,
                        saldo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertaCuentaAsync(int cuenta, decimal saldo) {
            this.InsertaCuentaAsync(cuenta, saldo, null);
        }
        
        /// <remarks/>
        public void InsertaCuentaAsync(int cuenta, decimal saldo, object userState) {
            if ((this.InsertaCuentaOperationCompleted == null)) {
                this.InsertaCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertaCuentaOperationCompleted);
            }
            this.InvokeAsync("InsertaCuenta", new object[] {
                        cuenta,
                        saldo}, this.InsertaCuentaOperationCompleted, userState);
        }
        
        private void OnInsertaCuentaOperationCompleted(object arg) {
            if ((this.InsertaCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertaCuentaCompleted(this, new InsertaCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertaCheque", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertaCheque(int cuenta, string numero) {
            object[] results = this.Invoke("InsertaCheque", new object[] {
                        cuenta,
                        numero});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertaChequeAsync(int cuenta, string numero) {
            this.InsertaChequeAsync(cuenta, numero, null);
        }
        
        /// <remarks/>
        public void InsertaChequeAsync(int cuenta, string numero, object userState) {
            if ((this.InsertaChequeOperationCompleted == null)) {
                this.InsertaChequeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertaChequeOperationCompleted);
            }
            this.InvokeAsync("InsertaCheque", new object[] {
                        cuenta,
                        numero}, this.InsertaChequeOperationCompleted, userState);
        }
        
        private void OnInsertaChequeOperationCompleted(object arg) {
            if ((this.InsertaChequeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertaChequeCompleted(this, new InsertaChequeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExisteTarjeta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ExisteTarjeta(string tarjeta) {
            object[] results = this.Invoke("ExisteTarjeta", new object[] {
                        tarjeta});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ExisteTarjetaAsync(string tarjeta) {
            this.ExisteTarjetaAsync(tarjeta, null);
        }
        
        /// <remarks/>
        public void ExisteTarjetaAsync(string tarjeta, object userState) {
            if ((this.ExisteTarjetaOperationCompleted == null)) {
                this.ExisteTarjetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExisteTarjetaOperationCompleted);
            }
            this.InvokeAsync("ExisteTarjeta", new object[] {
                        tarjeta}, this.ExisteTarjetaOperationCompleted, userState);
        }
        
        private void OnExisteTarjetaOperationCompleted(object arg) {
            if ((this.ExisteTarjetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExisteTarjetaCompleted(this, new ExisteTarjetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizaSaldoTarjeta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ActualizaSaldoTarjeta(string tarjeta, decimal monto) {
            object[] results = this.Invoke("ActualizaSaldoTarjeta", new object[] {
                        tarjeta,
                        monto});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizaSaldoTarjetaAsync(string tarjeta, decimal monto) {
            this.ActualizaSaldoTarjetaAsync(tarjeta, monto, null);
        }
        
        /// <remarks/>
        public void ActualizaSaldoTarjetaAsync(string tarjeta, decimal monto, object userState) {
            if ((this.ActualizaSaldoTarjetaOperationCompleted == null)) {
                this.ActualizaSaldoTarjetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizaSaldoTarjetaOperationCompleted);
            }
            this.InvokeAsync("ActualizaSaldoTarjeta", new object[] {
                        tarjeta,
                        monto}, this.ActualizaSaldoTarjetaOperationCompleted, userState);
        }
        
        private void OnActualizaSaldoTarjetaOperationCompleted(object arg) {
            if ((this.ActualizaSaldoTarjetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizaSaldoTarjetaCompleted(this, new ActualizaSaldoTarjetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RealizaRebajoTarjeta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RealizaRebajoTarjeta(string tarjeta, decimal monto) {
            object[] results = this.Invoke("RealizaRebajoTarjeta", new object[] {
                        tarjeta,
                        monto});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RealizaRebajoTarjetaAsync(string tarjeta, decimal monto) {
            this.RealizaRebajoTarjetaAsync(tarjeta, monto, null);
        }
        
        /// <remarks/>
        public void RealizaRebajoTarjetaAsync(string tarjeta, decimal monto, object userState) {
            if ((this.RealizaRebajoTarjetaOperationCompleted == null)) {
                this.RealizaRebajoTarjetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRealizaRebajoTarjetaOperationCompleted);
            }
            this.InvokeAsync("RealizaRebajoTarjeta", new object[] {
                        tarjeta,
                        monto}, this.RealizaRebajoTarjetaOperationCompleted, userState);
        }
        
        private void OnRealizaRebajoTarjetaOperationCompleted(object arg) {
            if ((this.RealizaRebajoTarjetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RealizaRebajoTarjetaCompleted(this, new RealizaRebajoTarjetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidaTarjeta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ValidaTarjeta(string tarjeta, string mes, string year, string cvv) {
            object[] results = this.Invoke("ValidaTarjeta", new object[] {
                        tarjeta,
                        mes,
                        year,
                        cvv});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ValidaTarjetaAsync(string tarjeta, string mes, string year, string cvv) {
            this.ValidaTarjetaAsync(tarjeta, mes, year, cvv, null);
        }
        
        /// <remarks/>
        public void ValidaTarjetaAsync(string tarjeta, string mes, string year, string cvv, object userState) {
            if ((this.ValidaTarjetaOperationCompleted == null)) {
                this.ValidaTarjetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidaTarjetaOperationCompleted);
            }
            this.InvokeAsync("ValidaTarjeta", new object[] {
                        tarjeta,
                        mes,
                        year,
                        cvv}, this.ValidaTarjetaOperationCompleted, userState);
        }
        
        private void OnValidaTarjetaOperationCompleted(object arg) {
            if ((this.ValidaTarjetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidaTarjetaCompleted(this, new ValidaTarjetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertaTarjeta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertaTarjeta(string nombreAsociado, string tarjeta, string mes, string year, string cvv, int tipo, decimal saldo) {
            object[] results = this.Invoke("InsertaTarjeta", new object[] {
                        nombreAsociado,
                        tarjeta,
                        mes,
                        year,
                        cvv,
                        tipo,
                        saldo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertaTarjetaAsync(string nombreAsociado, string tarjeta, string mes, string year, string cvv, int tipo, decimal saldo) {
            this.InsertaTarjetaAsync(nombreAsociado, tarjeta, mes, year, cvv, tipo, saldo, null);
        }
        
        /// <remarks/>
        public void InsertaTarjetaAsync(string nombreAsociado, string tarjeta, string mes, string year, string cvv, int tipo, decimal saldo, object userState) {
            if ((this.InsertaTarjetaOperationCompleted == null)) {
                this.InsertaTarjetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertaTarjetaOperationCompleted);
            }
            this.InvokeAsync("InsertaTarjeta", new object[] {
                        nombreAsociado,
                        tarjeta,
                        mes,
                        year,
                        cvv,
                        tipo,
                        saldo}, this.InsertaTarjetaOperationCompleted, userState);
        }
        
        private void OnInsertaTarjetaOperationCompleted(object arg) {
            if ((this.InsertaTarjetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertaTarjetaCompleted(this, new InsertaTarjetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtieneSaldoTarjeta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal ObtieneSaldoTarjeta(string tarjeta) {
            object[] results = this.Invoke("ObtieneSaldoTarjeta", new object[] {
                        tarjeta});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void ObtieneSaldoTarjetaAsync(string tarjeta) {
            this.ObtieneSaldoTarjetaAsync(tarjeta, null);
        }
        
        /// <remarks/>
        public void ObtieneSaldoTarjetaAsync(string tarjeta, object userState) {
            if ((this.ObtieneSaldoTarjetaOperationCompleted == null)) {
                this.ObtieneSaldoTarjetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtieneSaldoTarjetaOperationCompleted);
            }
            this.InvokeAsync("ObtieneSaldoTarjeta", new object[] {
                        tarjeta}, this.ObtieneSaldoTarjetaOperationCompleted, userState);
        }
        
        private void OnObtieneSaldoTarjetaOperationCompleted(object arg) {
            if ((this.ObtieneSaldoTarjetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtieneSaldoTarjetaCompleted(this, new ObtieneSaldoTarjetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void ValidateConnectionCompletedEventHandler(object sender, ValidateConnectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateConnectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateConnectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void ExisteCuentaCompletedEventHandler(object sender, ExisteCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExisteCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExisteCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void ExisteChequeCompletedEventHandler(object sender, ExisteChequeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExisteChequeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExisteChequeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void RealizaRebajoChequeCompletedEventHandler(object sender, RealizaRebajoChequeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RealizaRebajoChequeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RealizaRebajoChequeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void ActualizaSaldoChequeCompletedEventHandler(object sender, ActualizaSaldoChequeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizaSaldoChequeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizaSaldoChequeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void InsertaCuentaCompletedEventHandler(object sender, InsertaCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertaCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertaCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void InsertaChequeCompletedEventHandler(object sender, InsertaChequeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertaChequeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertaChequeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void ExisteTarjetaCompletedEventHandler(object sender, ExisteTarjetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExisteTarjetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExisteTarjetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void ActualizaSaldoTarjetaCompletedEventHandler(object sender, ActualizaSaldoTarjetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizaSaldoTarjetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizaSaldoTarjetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void RealizaRebajoTarjetaCompletedEventHandler(object sender, RealizaRebajoTarjetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RealizaRebajoTarjetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RealizaRebajoTarjetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void ValidaTarjetaCompletedEventHandler(object sender, ValidaTarjetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidaTarjetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidaTarjetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void InsertaTarjetaCompletedEventHandler(object sender, InsertaTarjetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertaTarjetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertaTarjetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void ObtieneSaldoTarjetaCompletedEventHandler(object sender, ObtieneSaldoTarjetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtieneSaldoTarjetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtieneSaldoTarjetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
}
